### ISSUE TITLE
List of different modules that can be added to the 3KEncoder to make our life easy

### ISSUE THREAD

**Issue by shis63032** [simon300000/3KEncoder#2]
Volume control = https://github.com/LinusU/node-loudness

Music Function control (Music player essentially) = https://github.com/goldfire/howler.js

I have made a branch for typed.js because I think this is necessary. (Skip, auto, etc are available too)
https://github.com/mattboldt/typed.js

**Comment by shis63032** [comment]
Typed.js also supports Vue components

https://github.com/Orlandster/vue-typed-js

**Comment by simon300000** [comment]
This is the encoder, encoder won't run during the game.
Please add this to ccp it self.
